# Generated by Django 4.2.8 on 2024-03-16 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, related_name='multi_valued_attribute_value', to='catalog.optiongroupvalues'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.optiongroupvalues'),
        ),
    ]
