# Generated by Django 4.2.8 on 2024-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_attributevalue_value_multi_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='catalog.category'),
        ),
    ]
