# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
    -  id: check-yaml
    -  id: check-added-large-files
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      name: flake8
      additional_dependencies:
        - flake8-bugbear
        - flake8-polyfill
      args: [
        "--config=./configs/.flake8"
      ]
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort
      args: [
        "--settings=./configs/.isort.cfg",
        --check-only,
        --diff,
      ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
    - id: mypy
      name: mypy
      additional_dependencies:
        - django-stubs >= 4.2.6, < 4.3
        - django-environ >= 0.11.2, < 0.12
        - djangorestframework-stubs >= 3.14.4, < 3.15
        - djangorestframework >= 3.14.0, < 3.15
        - django-filter >= 23.4.0, < 23.5
        - django-celery-results >= 2.5.1, < 2.6
        - django-celery-beat >= 2.5.0, < 2.6
        - django-cors-headers >= 4.3.1, < 4.4
        - django-extensions >= 3.2.3, < 3.3
        - psycopg2 >= 2.9.9, < 3.0
        - drf-spectacular >= 0.26.5, < 0.27
        - boto3-stubs >= 1.29.6, < 1.30
        - types-psycopg2 >= 2.9.21.19, < 2.10
        - whitenoise >= 6.6.0, < 6.7
        - pytest >= 7.4.3, < 7.5
        - Faker >= 20.1.0, < 20.2
      exclude: '^markdown_tools/'
      args: [
        "--config-file=./configs/mypy.ini",
        ]
