name: Checks

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test-Lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build env File
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > .env
      - name: Debug Logging
        run: |
          ls -l /project/configs    # Check directory listing and permissions
          echo "Checking .coverage file existence:"
          ls -l /project/configs/.coverage   # Check .coverage file and permissions
      - name: Test
        run: make cicd-pytest
      - name: Lint
        run: make cicd-flake8
      - name: Type Checking
        run: make cicd-mypy
