name: Checks

on:
  push:
    branches: [ "development", "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Test-Lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build env File
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > .env
      - name: Setup Docker-Compose
        run: make docker-compose-build
      - name: Setup permissions
        run: docker compose -f docker-compose.dev.yml exec django sh -c "chmod -R 777 /project/configs"
      - name: Print filesystem
        run: |
          docker exec -it djshop_django mount
          docker inspect djshop_django
      - name: Test
        run: make pytest
      - name: Lint
        run: make flake8
      - name: Type Checking
        run: make mypy
