# Generated by Django 4.2.8 on 2024-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_baseuser_created_by_alter_baseuser_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
